# Generated by Django 4.1.4 on 2023-10-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0002_tutorial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
