# Generated by Django 4.1.4 on 2023-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0005_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(default='images/Projectile Shooter.png', upload_to='images/'),
        ),
    ]
