# Generated by Django 4.1.4 on 2023-10-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0006_tutorial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='New Headlines', max_length=200),
        ),
    ]
