# Generated by Django 4.1.4 on 2023-10-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0007_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstext',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tuturials.news'),
            preserve_default=False,
        ),
    ]
