# Generated by Django 4.1.4 on 2023-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0008_newstext_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtext',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='image',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='image',
            name='tutorial',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newstext',
            name='news',
        ),
        migrations.RemoveField(
            model_name='note',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='note',
            name='tutorial',
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_pdfs/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_pdfs/'),
        ),
        migrations.AddField(
            model_name='news',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='news_pdfs/'),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
        migrations.DeleteModel(
            name='BlogText',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='NewsImage',
        ),
        migrations.DeleteModel(
            name='NewsText',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
