# Generated by Django 4.1.4 on 2023-10-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0009_remove_blogtext_blog_remove_image_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='source_code',
            field=models.FileField(blank=True, null=True, upload_to='source_code/'),
        ),
    ]
