# Generated by Django 4.1.4 on 2023-10-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0011_tutorialchapter_tutorialchaptercontent_delete_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialchaptercontent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
