# Generated by Django 4.1.4 on 2023-10-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0013_alter_tutorialchaptercontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialchaptercontent',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
