# Generated by Django 4.1.4 on 2023-10-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0014_alter_tutorialchaptercontent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialchaptercontent',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
