# Generated by Django 4.1.4 on 2023-10-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0015_tutorialchaptercontent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialchaptercontent',
            name='code_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
