# Generated by Django 4.1.4 on 2023-10-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tuturials', '0016_tutorialchaptercontent_code_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialchaptercontent',
            name='code_file_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialchaptercontent',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TutorialSourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tuturials.tutorial')),
            ],
        ),
    ]
